services:
  db:
    image: postgres:16.0-alpine
    environment:
      IN_DOCKER: "True"
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5433:5432"
    healthcheck:
      test: bash -c 'pg_isready -U ${DB_USER} -d ${DB_NAME}'
      interval: 10s
      timeout: 5s
      retries: 5

  web:
#    build: .
    env_file:
      - .env
    environment:
      IN_DOCKER: "True"
      DB_HOST: db
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: "5432"
      REDIS_HOST: redis://redis:6379
    command: sh -c "
      python manage.py collectstatic --noinput &&
      python manage.py migrate &&
      python manage.py cau &&
      gunicorn habit_tracker.wsgi:application --bind 0.0.0.0:8000
      "
    volumes:
      - static_volume:/code/collected_static
      - media_volume:/code/media
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8000:8000"

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/collected_static
    depends_on:
      - web

  redis:
    image: redis:7.2.4-alpine
    env_file:
      - .env
    environment:
      IN_DOCKER: "True"
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - "./config/redis.conf:/usr/local/etc/redis/redis.conf"
      - redis_data:/data
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 1s
      retries: 5

  celery:
    image: ${APP_IMAGE:-habit_tracker}:${IMAGE_TAG:-latest}
    env_file:
      - .env
    environment:
      IN_DOCKER: "True"
    command: bash -c "celery -A habit_tracker worker -l info"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "pgrep", "celery"]
      interval: 10s
      timeout: 5s
      retries: 3

  beat:
    image: ${APP_IMAGE:-habit_tracker}:${IMAGE_TAG:-latest}
    env_file:
      - .env
    environment:
      IN_DOCKER: "True"
    command: >
      bash -c "
        echo 'Waiting for DB migrations to be applied...' &&
        until python /code/manage.py migrate --list > /dev/null 2>&1; do
          sleep 5
        done &&
        echo 'Migrations are ready. Starting celery beat...' &&
        celery -A habit_tracker beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
      "
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy


volumes:
  postgres_data:
  static_volume:
  media_volume:
  redis_data: