# Generated by Django 5.2.10 on 2026-01-29 18:39

import datetime

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("action", models.CharField(max_length=200, verbose_name="Действие")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                (
                    "last_notified_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Время последнего оповещения"),
                ),
                (
                    "date_start",
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name="Дата и время начала"),
                ),
                (
                    "date_end",
                    models.DurationField(default=datetime.timedelta(days=30), verbose_name="Период действия"),
                ),
                ("location", models.CharField(max_length=200, verbose_name="Место")),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=12, null=True, verbose_name="Номер телефона"),
                ),
                (
                    "periodicity_days",
                    models.DurationField(default=datetime.timedelta(days=1), verbose_name="Периодичность (дни)"),
                ),
                ("reward", models.CharField(blank=True, max_length=200, null=True, verbose_name="Вознаграждение")),
                (
                    "time_to_complete",
                    models.DurationField(default=datetime.timedelta(seconds=120), verbose_name="Время на выполнение"),
                ),
                ("is_pleasant", models.BooleanField(default=False, verbose_name="Приятная привычка")),
                ("is_public", models.BooleanField(default=False, verbose_name="Публичная")),
                ("is_active", models.BooleanField(default=True, verbose_name="Активна")),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
                "ordering": ("date_start",),
            },
        ),
    ]
