# Generated by Django 6.0.1 on 2026-02-01 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="habit",
            name="phone_number",
        ),
    ]
